### ISSUE TITLE
Direct Messaging (Chat)

### ISSUE THREAD

**Issue by Shawn-3604** [mnaimhaziq/Chirper#8]
a way for users to have one-on-one or group conversations without the content being visible to the public.

**Comment by mekukun** [comment]
### **Some issues found**

#### Issue 1
Issue: Error : Connection to "http://localhost:3001/socket.io/..." refused.
How to replicate bug : Be in /direct-message endpoint.
Suspect component : UserChatCard.tsx
![image](https://github.com/mnaimhaziq/Chirper/assets/71602023/5f74c020-61d0-48b2-9f83-800e778186ef)

#### Issue 2
Issue: Error : Connection to "http://localhost:3001/socket.io/..." refused.
How to replicate bug : Be in /direct-message/{id} endpoint.
Suspect component : Chat.tsx
![image](https://github.com/mnaimhaziq/Chirper/assets/71602023/7930b207-17f2-40c5-9f09-cbd2c6da47f4)

#### Issue 3
Issue: Navigation bar don't work except Log Out after a message is sent.
How to replicate bug : Send a direct message once and try to use the navigation bar right after.

#### Issue 4
Issue: Runtime error : TypeError: Cannot read properties of undefined (reading 'map')
How to replicate bug : Send a direct message once and click on Log Out button from the navigation bar right after.
Suspect component : Chat.tsx
Solution suggestion : put "?" after "messages" to handle null value. E.g. "messages?.map((message) =>..."
![image](https://github.com/mnaimhaziq/Chirper/assets/71602023/bd8113b8-8bd3-4247-906d-b2be755fd879)
